<?php

namespace AppBundle\Repository;

/**
 * ChiTietHDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiTietHDRepository extends \Doctrine\ORM\EntityRepository
{
}
