<?php

namespace AppBundle\Repository;

/**
 * HoaDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoaDonRepository extends \Doctrine\ORM\EntityRepository
{
	public function DoanhThuNam($nam)
	{
		return $this->getEntityManager()->createQuery(

			'SELECT MONTH(h.ngaygiao) AS thang, SUM(h.tongtien) AS tongtien 
			FROM AppBundle:HoaDon h
			WHERE YEAR(h.ngaygiao) = :nam AND h.trangthai = :trangthai
			GROUP BY thang'
		)
		->setParameter('nam',$nam)->setParameter('trangthai','Đã giao')
		->getArrayResult();

	}
}

