<?php

namespace AppBundle\Repository;

/**
 * HoaDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoaDonRepository extends \Doctrine\ORM\EntityRepository
{
}
