<?php

namespace AppBundle\Repository;

/**
 * KhachHangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KhachHangRepository extends \Doctrine\ORM\EntityRepository
{
}
