<?php

namespace AppBundle\Repository;

/**
 * KhoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KhoRepository extends \Doctrine\ORM\EntityRepository
{
}
