<?php

namespace AppBundle\Repository;

/**
 * LoaiSPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoaiSPRepository extends \Doctrine\ORM\EntityRepository
{
}
