<?php

namespace AppBundle\Repository;

/**
 * SanPhamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanPhamRepository extends \Doctrine\ORM\EntityRepository
{
}
