# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loader
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /sanpham
                username_parameter: _username
                password_parameter: _password
            logout:
                path: /logout
                target: /login
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
